### ISSUE TITLE
[QUESTION] How to use this boilerplate properly?

### ISSUE THREAD

**Issue by albodelu** [bufferapp/android-clean-architecture-boilerplate#12]
Thank you for creating this awesome project and the lovely documentation and art!

I am worried about the best way to include or start a derived professional app using AL 2.0.

I know the licenses are compatible, but I would like to do it correctly and don't delete the docs.

So new developers that continue the project understand the architecture easily and check changes.

I want to avoid starting from scratch, so I would like to: 
- Move the license.txt and readme.md to a documentation folder and link to it from the new one.
- Rename packages.
- Include the buffer sample temporarily until I finish my tested alternative.
- Delete buffer*-related code.
- Create proper credits to Buffer in documentation folder or a better and recommended place.

I am going to use this project in my personal apps, but I am worried about apps for clients.

I am planning to contribute so guidelines about style and this topic would be appreciated.

**Comment by ravidsrk** [comment]
@albodelu If you want to create new project using this boilerplate, Please check http://androidstarters.com/

**Comment by albodelu** [comment]
Thank you @ravidsrk, but your version is outdated now, are you planning to keep it up-to-date?.

The idea is to create a mirror and keep it also as a remote, so I can compare and contribute via git.
