### ISSUE TITLE
JSON link dead

### ISSUE THREAD

**Issue by pawelkw** [bufferapp/android-clean-architecture-boilerplate#17]
Looks like
https://joe-birch-dsdb.squarespace.com/s/team-abk9.json
is not there anymore...

**Comment by hitherejoe** [comment]
Oops sorry about that! Is fixed now :)

**Comment by bmschwartz** [comment]
Looks like it went down again :)

**Comment by jessicalorenac** [comment]
Hi guys, Looks like https://joe-birch-dsdb.squarespace.com/s/team-abk9.json went down again, could you please update it?

**Comment by ghost** [comment]
Related issue: https://github.com/bufferapp/android-clean-architecture-boilerplate/issues/54

**Comment by tungamiraimujuru** [comment]
@hitherejoe  The link following link is dead: https://joe-birch-dsdb.squarespace.com/s/team.json

**Comment by vinhbpt-teko** [comment]
Anyone can send me json file ???
