### ISSUE TITLE
Gradle dependencies don't get warnings about new version

### ISSUE THREAD

**Issue by kalmanbencze** [bufferapp/android-clean-architecture-boilerplate#18]
I have implemented the gradle dependency template from the project and after a while I noticed that you dont get prompted anymore about new versions. AS doesn't recognise the patterns since it is broken down to multiple variables. Is this something we will have to learn to ignore or is there a way to make it work again without reverting to hardcoded dependencies?

**Comment by adrian110288** [comment]
This really bugs me too! I don't see any way around it atm and I am learning to ignore that hoping there will be solution

**Comment by christxph** [comment]
You can add the [Gradle Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin) to your project and get a list of updatable dependencies by running the `dependencyUpdates` task
