### ISSUE TITLE
DataStore question

### ISSUE THREAD

**Issue by jemshit** [bufferapp/android-clean-architecture-boilerplate#21]
Hi, i have a question. Why did you introduce `DataStore` classes, instead of using `DataSource` itself? 

What is the gain of adding one more abstraction, `DataSource` is already interface and `Repository` would not be depended on Implementation any way?

**Comment by anstaendig** [comment]
The repository is meant for passing data to and from the domain layer whereas `DataSource`s are for pure data operations. The way I see it a `Repository` has a one-to-many relation to `DataSource` hence the abstraction? That's just my opinion though.

**Comment by jemshit** [comment]
@anstaendig you got it wrong, i asked why there is Data**Store**, why not just Data**Source**

**Comment by anstaendig** [comment]
Wait, am I mixing something up here? There's no such thing as a DataSource interface?! Can you clarify?

**Comment by jemshit** [comment]
[In this pic](https://raw.githubusercontent.com/bufferapp/android-clean-architecture-boilerplate/master/art/architecture.png), you can see it. In code, they should be [BufferooCache](https://github.com/bufferapp/android-clean-architecture-boilerplate/blob/master/data/src/main/java/org/buffer/android/boilerplate/data/repository/BufferooCache.kt) and [BufferooRemote](https://github.com/bufferapp/android-clean-architecture-boilerplate/blob/master/data/src/main/java/org/buffer/android/boilerplate/data/repository/BufferooRemote.kt)
Why not [this approach](https://github.com/android10/Android-CleanArchitecture/tree/master/data/src/main/java/com/fernandocejas/android10/sample/data/repository/datasource) ?

**Comment by anstaendig** [comment]
Ah, now I get it. I think the reason is that with one more layer of abstraction you have the freedom to implement the `DataSource`s in different ways and then have one interface via the `DataStore`. With the approach you mentioned all `DataStore`s have the same interface. The approach in here has the flexibility to have different interfaces for cache and data. 

I hope I did not mix up things again but now it seems plausible :D

**Comment by jemshit** [comment]
With approach i mentioned, you only may have some empty methods in Local or Remote DataSource. But to overcome that, introducing one more abstraction and 2 different interfaces does not look attractive to me :)

**Comment by hitherejoe** [comment]
This is optional. If you have one interface shared between the cache and remote stores then you could end up having a lot of unused methods. The difference between the cache interface and the remote interface is quite a lot, meaning that they'd be a lot of unused bloat in the remote implementation class. THis is likely just personal preference though, no big deal what you go for either way :)

**Comment by jemshit** [comment]
Ok 👍
