### ISSUE TITLE
How does BrowseAdapter inject automatically without any @Provide method?

### ISSUE THREAD

**Issue by meness** [bufferapp/android-clean-architecture-boilerplate#53]
Hi,

I wonder how does `BrowseAdapter` inject automatically without any `@Provide` method?

**Comment by AldrichMascarenhas** [comment]
BrowseAdapter has @Inject at the constructor

**Comment by ghost** [comment]
Check for annotation processors info: https://google.github.io/dagger/users-guide.html. Hope it will help :-)
