### ISSUE TITLE
LastCacheTime will be updated even if data is accessed from CacheDataStore?

### ISSUE THREAD

**Issue by jdsingh** [bufferapp/android-clean-architecture-boilerplate#8]
https://github.com/bufferapp/android-clean-architecture-boilerplate/blob/f036554fcd5c43bd518a1a4c242d5406cbe681af/data/src/main/java/org/buffer/android/boilerplate/data/BufferooDataRepository.kt#L31

I think there is some problem here. If I understand it correctly when the `factory.retrieveDataStore()` returns the `BufferooCacheDataStore` then this code is just taking the data from the cache and again storing it in the cache and updating `LastCacheTime`. 

This does not feel right. Is this intended behavior or some sort of issue?

**Comment by hitherejoe** [comment]
Oops, that's my bad - will fix that up today :) Good spot!
